abcdosaber/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tipoatividade/', include('tipodeatividade.urls', namespace= 'tipodeatividade')),
    path('instrutores/', include('instrutores.urls')),
    path('aluno/', include('aluno.urls', namespace='aluno')),
    path('turmas/', include('turmas.urls', namespace='turmas')),
    path('titulo/', include('titulo.urls', namespace='titulo')),
    path('', TemplateView.as_view(template_name="escola.html")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aluno/urls.py
from django.urls import path
from . import views

app_name= 'aluno'

urlpatterns = [

    path('lista/', views.listar, name='listar'),

] 

instrutores/urls.py
from django.urls import path
from . import views

app_name='instrutores'

urlpatterns = [
    path('lista/', views.listar, name='listar'),
    path('cadastro/', views.carregar_cadastro, name = 'cadastro'),
    path('cadastrar/', views.cadastrar, name = 'cadastrar'),
] 

instrutores/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone

from titulo.models import Titulo

# Create your models here.
class Instrutores (models.Model):
    """Modelo representando os instrutores"""
    Id = models.AutoField(primary_key=True,
                                 help_text='Identificação do Instrutor')
    rg = models.CharField(max_length=15, null=True,
                                 help_text='Informe a região do instrutor')
    nome = models.CharField(max_length=70, null=False,
                                 help_text='Informe a descrição do instrutor')
    dataNascimento = models.DateField(null=True, blank=True,
                                    help_text='Informe a Data de Nascimento do Instrutor')
    telefone = models.CharField(max_length=9, null=True,
                                 help_text='Informe telefone de contato dos instrutores')
    ddd = models.CharField(max_length=3, null=True,
                                 help_text='Informe código de área dos instrutores')
    codigo_titulo = models.ForeignKey(Titulo,
                                      null=True,
                                      blank=True,
                                      on_delete=models.SET_NULL,
                                      db_column='titulo_codigo'
                                      )
   
        
    def __str__(self):
        return f'{self.codigo} {self.descricao}'

instrutores/forms.py
from django import forms

class InstrutoresForm(forms.Form):
    rg = forms.CharField(max_length=15, required=False, help_text="Informe o RG do Instrutor")
    nome = forms.CharField(max_length= 70, required=False, help_text="Informe o nome do Instrutor")
    data_Nascimento = forms.DateField(required=True, help_text="Informe a data de nascimento do Instrutor")
    telefone = forms.CharField(max_length=9, required=False, help_text="Informe o Número de telefone do Intrutor")
    ddd = forms.CharField(max_length=3, required=False, help_text="Informe o Número de ddd do Intrutor")
    codigo_titulo = forms.IntegerField(required=True, help_text="Informe o Título do Instrutor")
    

instrutores/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.forms import forms
from instrutores.models import Instrutores
from titulo.models import Titulo
from instrutores.forms import InstrutoresForm



# Create your views here.

def listar(request):
    lista_instrutores = Instrutores.objects.all()
    contexto = {
        'instrutores': lista_instrutores

    }
    return render(request, 'instrutores/listarinstrutores.html', context=contexto)

def carregar_cadastro(request):
    lista_titulos = Titulo.objects.all()
    contexto = {
        'titulos': lista_titulos
    }
    return render(request, 'instrutores/cadastrarInstrutores.html', context=contexto)

def cadastrar(request):
    form = InstrutoresForm(request.POST)
    if form.is_valid():
        dados_intrutores = form.cleaned_data
        titulo = Titulo.objects.get(pk=dados_intrutores["codigo_titulo"])
        
        instrutores = Instrutores(
            id = dados_intrutores["id"],
            rg = dados_intrutores["rg"],
            nome = dados_intrutores["nome"],
            data_nascimento = dados_intrutores["data_nascimento"],
            telefone = dados_intrutores["telefone"],
            ddd = dados_intrutores["ddd"],
            codigo_titulo = titulo, 
            
            
            descricao = dados_intrutores['descricao'],
        )
        instrutores.save()
        
    return render(request, 'instrutores/cadastrarInstrutores.html')

instrutores/templates/instrutores/cadastrarInstrutores.html
{% extends "base_templates.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'instrutores:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'instrutores:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}

{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Cadastro de Titulo</h2>
        </div>
    </div>

    <form name="frmCadastrarInstrutor" action="#" method="post" class="my-label-color-purple">
        {% csrf_token %}
        <div class="form-group">
            <label for="idNomeInstrutor" class="col-form-label">Nome do Instrutor</label>
            <input class="form-control" type="text" id="idNomeInstrutor" name="nome"
                placeholder="Informe o nome do instrutor" maxlength="70" required>
        </div>

        <div class="form-group">
            <label for='idRg'>RG</label>
            <input class="form-control" type='text' id='idRg' name='rg' placeholder="Informe o RG" maxlength="45"
                required>
        </div>

        <div class="form-group">
            <label for='idDataNascimento'>Data de Nascimento</label>
            <input class="form-control" type='date' id='idDataNascimento' name='data_Nascimento' required>
        </div>

        <div class="form-group row">
            <div class="col-sm-6">
                <label for='idDdd'>DDD</label>
                <input class="form-control" type='ddd' id='idDataNascimento' name='ddd' maxlength="3" required>
            </div>
            <div class="col-sm-6">
                <label for='idTelefone'>Telefone</label>
                <input class="form-control" type='text' id='idTelefone' name='telefone' maxlength="9" required>
            </div>
        </div>

        <div class="form-group">
            <label for="idTitulo">Título do Professor</label>
            <select class="form-control" id="idTitulo" name="codigoTitulo">
                <option value="0">Selecione...</option>

                {% for t in titulos %}
                    <option value= "{{ t.codigo }}">{{ t.descricao}}</option>
                {% endfor %}
             
            </select>
        </div>

        <div class="form-group my-4 text-center">
            <input type="reset" value="Limpar" class="btn btn-primary btn-md">
            <input type="submit" value="Cadastrar" class="btn btn-primary btn-md">
        </div>

    </form>

</main>


{% endblock %}

instrutores/templates/instrutores/listarinstrutores.html
{% extends "base_templates.html" %}


{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}


{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'instrutores:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'instrutores:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}


{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Lista de Instrutor</h2>
        </div>
    </div>

    <!-- tabela responsiva -->
     {% if instrutores %}
    <div class="table-responsive">

        <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
        <table class="table
                    table-borderless
                    text-center
                    my-table-hover
                    my-table-image
                    my-table-td-first-child
                    my-table-border-bottom
                    my-table-th
                    w-100">

            <!-- cabecalho -->
            <thead>
                <!-- linhas -->
                <tr>
                    <!-- colunas cabecalho -->
                    <th>id</th>
                    <th>rg </th>
                    <th>nome </th>                    
                    <th>dataNascimento</th>
                    <th>telefone</th>
                    <th>ddd </th>
                    <th>titulo </th>
                </th>
            </thead>

            <!-- linhas -->
             {% for i in instrutores %}
            <tr>
                <td> {{ i.Id}} </td>
                <td> {{ i.rg}} </td>
                <td> {{ i.nome }} </td>
                <td> {{ i.dataNascimento }} </td>
                <td> {{ i.telefone }} </td>
                <td> {{ i.ddd }} </td>
                <td> {{ i.titulo_codigo.descricao }} </td>
                               
                
            </tr>

            {% endfor %}
            
        </table>

    </div>

    {% else %}

    <div class = "text-danger">
        <p> Não há Titulo Cadastrado.</p>
    </div>

    {% endif %}
    

</main>


{% endblock %}