abcdosaber/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tipoatividade/', include('tipodeatividade.urls', namespace= 'tipodeatividade')),
    path('instrutores/', include('instrutores.urls')),
    path('aluno/', include('aluno.urls', namespace='aluno')),
    path('turmas/', include('turmas.urls', namespace='turmas')),
    path('titulo/', include('titulo.urls', namespace='titulo')),
    path('', TemplateView.as_view(template_name="escola.html")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aluno/urls.py
from django.urls import path
from . import views

app_name= 'aluno'

urlpatterns = [

    path('lista/', views.listar, name='listar'),

] 

titulo/urls.py
from django.urls import path
from . import views

app_name = 'titulo'

urlpatterns = [
    path('lista/', views.listar, name='listar'),
    path('cadastro/', views.carregar_cadastro, name = 'cadastro'),
    path('cadastrar/', views.cadastrar, name = 'cadastrar'),
] 

titulo/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Titulo (models.Model):
    """Modelo representando um titulo"""
    codigo = models.AutoField(primary_key=True,
                              help_text='Código do titulo')
    descricao = models.CharField(max_length=100, null=False,
                                 help_text='Informe a descrição do titulo')
    
    def __str__(self):
        return f'{self.codigo} {self.descricao}'



titulo/forms.py
from django import forms

class TituloForm(forms.Form):
    descricao = forms.CharField(max_length=100, required = True,
                                 help_text='Informe a descrição do titulo')

titulo/views.py
from django.shortcuts import render
from django.http import HttpResponse

from titulo.models import Titulo
from titulo.forms import TituloForm

# Create your views here.
def listar(request):
    lista_titulo = Titulo.objects.order_by("descricao")
    contexto = {
            'titulo': lista_titulo
        }
    return render(request, 'titulo/listarTitulo.html', context = contexto)

def carregar_cadastro(request):
    
    return render(request, 'titulo/cadastrarTitulo.html')

def cadastrar(request):
    form = TituloForm(request.POST)
    if form.is_valid():
        dados_titulo = form.cleaned_data
        titulo = Titulo(
            descricao = dados_titulo['descricao']
        )
        titulo.save()
        
    return render(request, 'titulo/cadastrarTitulo.html')

titulo/templates/titulo/cadastrarTitulo.html
{% extends "base_templates.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'titulo:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'titulo:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}

{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Cadastro de Titulo</h2>
        </div>
    </div>

    <form action="{% url 'titulo:cadastrar' %}" method="POST" name="frmCadastrarTitulo" id="idFrmCadastrarTiposAtividade">
        {% csrf_token %}
        <div class="form-group">
            <label for='idDescricao'>Descrição</label>
            <input class="form-control" type='text' id='idDescricao' name='descricao' placeholder='Informe a descrição' required>
        </div>
        <div class='form-group text-center'>
            <input type='reset'  value='Limpar' class='btn btn-primary btn-md'>
            <input type='submit' value='Cadastrar' class='btn btn-primary btn-md' id="btnCadastrarTiposAtividade">
        </div>
    </form>

</main>


{% endblock %}

titulo/templates/titulo/listartitulo.html
{% extends "base_templates.html" %}


{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}


{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'titulo:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'titulo:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}


{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Lista de Titulo</h2>
        </div>
    </div>

    <!-- tabela responsiva -->
     {% if titulo %}
    <div class="table-responsive">

        <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
        <table class="table
                    table-borderless
                    text-center
                    my-table-hover
                    my-table-image
                    my-table-td-first-child
                    my-table-border-bottom
                    my-table-th
                    w-100">

            <!-- cabecalho -->
            <thead>
                <!-- linhas -->
                <tr>
                    <!-- colunas cabecalho -->
                    <th>Código</th>
                    <th>Descrição</th>
                </tr>
            </thead>

            <!-- linhas -->
             {% for t in titulo %}
            <tr>
                <td> {{ t.codigo}} </td>
                <td> {{ t.descricao }} </td>
                
            </tr>

            {% endfor %}
            
        </table>

    </div>

    {% else %}

    <div class = "text-danger">
        <p> Não há Titulo Cadastrado.</p>
    </div>

    {% endif %}
    

</main>


{% endblock %}