abcdosaber/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tipoatividade/', include('tipodeatividade.urls', namespace= 'tipodeatividade')),
    path('instrutores/', include('instrutores.urls')),
    path('aluno/', include('aluno.urls', namespace='aluno')),
    path('turmas/', include('turmas.urls', namespace='turmas')),
    path('titulo/', include('titulo.urls', namespace='titulo')),
    path('', TemplateView.as_view(template_name="escola.html")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

aluno/urls.py
from django.urls import path
from . import views

app_name= 'aluno'

urlpatterns = [

    path('lista/', views.listar, name='listar'),

] 

titulo/urls.py
from django.urls import path
from . import views

app_name = 'titulo'

urlpatterns = [
    path('lista/', views.listar, name='listar'),
    path('cadastro/', views.carregar_cadastro, name = 'cadastro'),
    path('cadastrar/', views.cadastrar, name = 'cadastrar'),
] 

turmas/urls.py
from django.urls import path
from . import views

app_name='turmas'

urlpatterns = [
    
    path('lista/', views.listar, name='listar'),


] 

turmas/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone


from tipodeatividade.models import TipoDeAtividade
from aluno.models import Aluno
from instrutores.models import Instrutores


"""Modelo representando um Turmas"""

class Turma(models.Model):
    numero = models.AutoField(primary_key=True, help_text="Informe a turma do Aluno")
    horario_aula = models.TimeField(help_text="Informe a hora em que a hora da aula da Turma")
    duracao_aula = models.SmallIntegerField(default=30, help_text="Informe a duração da aula da Turma")
    data_inicial = models.DateField(default=timezone.now, help_text="Informe a data inicial da Turma")    
    data_final = models.DateField(null=True,blank=True, help_text="Informe a data final da Turma")
    codigo_atividade = models.ForeignKey(TipoDeAtividade, on_delete=models.CASCADE)
    matricula_monitor = models.ForeignKey(Aluno, null=True, blank=True, on_delete=models.SET_NULL)
    id_instrutor = models.ForeignKey(Instrutores, null=True, on_delete=models.CASCADE)

    
    class Meta:
        ordering = ['numero']
    
    def str(self):
        return f'Turma: {self.numero} - Instrutor: {self.id_instrutor.nome} - Monitor: {self.matricula_monitor.nome}'


class TurmaAluno(models.Model):
    numero_turma = models.ForeignKey(Turma, on_delete=models.CASCADE, help_text="Turma do aluno.")
    matricula_aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE, help_text="Matrícula do aluno.")
    data_inicio_matricula = models.DateField(null=False, default=timezone.now,help_text="Data da matrícula do aluno.")
    data_fim_matricula= models.DateField(null=True, blank=True, help_text="Data fim de matrícula do aluno.")
    
    def __str__(self):
        resposta = f' Turma: {self.id} - Aluno: {self.matricula_aluno} - Matricula: {self.data_inicio_matricula.strftime("%d/%m/%y")}'
        data_fim_matricula = self.data_fim_matricula.strftime("%d/%m/%y") if self.data_fim_matricula else ''
        
        if data_fim_matricula:
            resposta += ' até ' + data_fim_matricula
            
        return resposta
    
class Ausencia(models.Model):
    numero_turma = models.ForeignKey(Turma, on_delete=models.CASCADE, help_text="Turma do aluno.")
    matricula_aluno = models.ForeignKey(Aluno, on_delete=models.CASCADE, help_text="Matrícula do aluno.")
    data_ausencia = models.DateField(null=False, 
                                     default=timezone.now,
                                     help_text="Data da falta do aluno da turma.")
    
    
    def str(self):
        resposta = f' Turma: {self.numero_turma} - Aluno: {self.matricula_aluno} - Ausencia: {self.data_ausencia.strftime("%d/%m/%y")}'
      
        return resposta

turmas/forms.py
from django import forms

turmas/views.py
from django.shortcuts import render
from django.http import HttpResponse

from turmas.models import Turma

# Create your views here.


def listar(request):
     lista_turma = Turma.objects.all()
     return HttpResponse("<!DOCType html><html><body><main><p style='color:blue;'>'Lista de Turmas' </p> <img src='https://i.pinimg.com/736x/56/a1/0b/56a10b873ffd997856d404fc23a1dd04.jpg'> </main> </body></html>")


turmas/templates/turmas/cadastrarTurmas.html
{% extends "base_templates.html" %}

{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}

{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'turmas:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'turmas:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}

{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Cadastro de Turmas</h2>
        </div>
    </div>

    <form action="{% url 'turmas:cadastrar' %}" method="POST" name="frmCadastrarturmas" id="idFrmCadastrarTiposAtividade">
        {% csrf_token %}
        <div class="form-group">
            <label for='idDescricao'>Descrição</label>
            <input class="form-control" type='text' id='idDescricao' name='descricao' placeholder='Informe a descrição' required>
        </div>
        <div class='form-group text-center'>
            <input type='reset'  value='Limpar' class='btn btn-primary btn-md'>
            <input type='submit' value='Cadastrar' class='btn btn-primary btn-md' id="btnCadastrarTiposAtividade">
        </div>
    </form>

</main>


{% endblock %}

turmas/templates/turmas/listarturmas.html
{% extends "base_templates.html" %}


{% block title %}
    <title>Django - Exercícios</title>
{% endblock %}


{% block menu %}
<div class="collapse navbar-collapse justify-content-end" id="mynavbar">
    <div class="navbar-nav">
        <a href="/" class="nav-link">Início</a>
        <a href="{% url 'turmas:cadastro'%}" class="nav-link">Cadastrar</a>
        <a href="{% url 'turmas:listar'%}" class="nav-link">Listar</a>
    </div>
</div>
{% endblock %}


{% block corpo %}
<main class="container m-2 mx-auto my-font-family">

    <div class="row">
        <div class="col text-center m-0">
            <h2 class="mt-2 mb-5 my-h2">Lista de Turmas/h2>
        </div>
    </div>

    <!-- tabela responsiva -->
     {% if turmas %}
    <div class="table-responsive">

        <!-- classes para tabela (Bootstrap) , tabela sem borda, conteudo alinhado ao centro, ... , width: auto -->
        <table class="table
                    table-borderless
                    text-center
                    my-table-hover
                    my-table-image
                    my-table-td-first-child
                    my-table-border-bottom
                    my-table-th
                    w-100">

            <!-- cabecalho -->
            <thead>
                <!-- linhas -->
                <tr>
                    <!-- colunas cabecalho -->
                    <th>Código</th>
                    <th>Descrição</th>
                </tr>
            </thead>

            <!-- linhas -->
             {% for t in turmas %}
            <tr>
                <td> {{ t.codigo}} </td>
                <td> {{ t.descricao }} </td>
                
            </tr>

            {% endfor %}
            
        </table>

    </div>

    {% else %}

    <div class = "text-danger">
        <p> Não há Turmas Cadastradas.</p>
    </div>

    {% endif %}
    

</main>


{% endblock %}